### ISSUE TITLE
converging time of the training

### ISSUE THREAD

**Issue by shimaashabani** [Xiong5Heng/GOPT#1]
Hello,
First and foremost, I would like to express my sincere gratitude for generously sharing your code.
I have encountered a question during my implementation. Despite utilizing a GeForce RTX 4090, a high-performance CPU, and 60 GB of RAM, after 3 hours of processing, only 30 epochs have been completed. Given this, it seems that running 1000 epochs would require a considerable amount of time. I am curious to understand how, as mentioned in the article, the training process for 1000 epochs was achieved within just 6 hours.

**Comment by Xiong5Heng** [comment]
Hi,
My server is equipped with RTX 3090 and Intel i7-14700K CPU (20 cores), and I think your server is better than mine. You can check 
1. whether conda environment is configured appropriately and do you use GPU for training?
2. I used 128 parallel environments, and the default number is 2, you need to set this parameter `num_processes` in the configuration file `cfg/config.yaml`.
